<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="UserInterface.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\PhoneBook.Core.fsproj" />
  </ItemGroup>
</Project>
